const BodyComponents = {
  Accordion: 'Accordion',
  AccordionElement: 'AccordionElement',
  AccordionTitle: 'AccordionTitle',
  AccordionText: 'AccordionText',
  Button: 'Button',
  Column: 'Column',
  Divider: 'Divider',
  Group: 'Group',
  Hero: 'Hero',
  Image: 'Image',
  Navbar: 'Navbar',
  Raw: 'Raw',
  Section: 'Section',
  Social: 'Social',
  Spacer: 'Spacer',
  Table: 'Table',
  Text: 'Text',
  Wrapper: 'Wrapper',
}

export const MjButton = {
  title: 'Button',
  tagName: 'mj-button',
  description: 'Displays a customizable button.',
  isEndingTag: true,
  allowedChildren: [],
  attributes: {
    align: {
      label: 'align',
      type: 'string',
      description: 'horizontal alignment',
      defaultValue: 'center',
    },
    'background-color': {
      label: 'background-color',
      unit: 'color',
      description: 'button background-color',
      defaultValue: '#414141',
    },
    border: {
      label: 'border',
      type: 'number',
      unit: 'px',
      description: 'css border format',
      defaultValue: 'none',
    },
    'border-bottom': {
      label: 'border-bottom',
      type: 'number',
      unit: 'px',
      description: 'css border format',
      defaultValue: null,
    },
    'border-left': {
      label: 'border-left',
      type: 'number',
      unit: 'px',
      description: 'css border format',
      defaultValue: null,
    },
    'border-radius': {
      label: 'border-radius',
      type: 'number',
      unit: 'px',
      description: 'border radius',
      defaultValue: '3px',
    },
    'border-right': {
      label: 'border-right',
      type: 'number',
      unit: 'px',
      description: 'css border format',
      defaultValue: null,
    },
    'border-top': {
      label: 'border-top',
      type: 'number',
      unit: 'px',
      description: 'css border format',
      defaultValue: null,
    },
    color: {
      label: 'color',
      unit: 'color',
      description: 'text color',
      defaultValue: '#ffffff',
    },
    'container-background-color': {
      label: 'container-background-color',
      unit: 'color',
      description: 'button container background color',
      defaultValue: null,
    },
    'css-class': {
      label: 'css-class',
      type: 'string',
      description: 'class name, added to the root HTML element created',
      defaultValue: null,
    },
    'font-family': {
      label: 'font-family',
      type: 'string',
      description: 'font name',
      defaultValue: 'Ubuntu, Helvetica, Arial, sans-serif',
    },
    'font-size': {
      label: 'font-size',
      unit: 'px',
      description: 'text size',
      defaultValue: '13px',
    },
    'font-style': {
      label: 'font-style',
      type: 'string',
      description: 'normal/italic/oblique',
      defaultValue: null,
    },
    'font-weight': {
      label: 'font-weight',
      unit: 'string',
      description: 'text thickness',
      defaultValue: 'normal',
    },
    height: {
      label: 'height',
      type: 'number/string',
      unit: 'px',
      description: 'button height',
      defaultValue: null,
    },
    href: {
      label: 'href',
      unit: 'link',
      description: 'link to be triggered when the button is clicked',
      defaultValue: null,
    },
    'inner-padding': {
      label: 'inner-padding',
      type: 'number',
      unit: 'px',
      description: 'inner button padding',
      defaultValue: '10px 25px',
    },
    'letter-spacing': {
      label: 'letter-spacing',
      type: 'number',
      unit: 'px/em',
      description: 'letter-spacing',
      defaultValue: null,
    },
    'line-height': {
      label: 'line-height',
      unit: 'px/%',
      description: 'line-height on link',
      defaultValue: '120%',
    },
    // 'padding': {
    // 'padding',
    //   type: 'number',
    //   unit: 'px',
    //   description: 'supports up to 4 parameters',
    //   defaultValue: '10px 25px',
    // },
    'padding-bottom': {
      label: 'padding-bottom',
      type: 'number',
      unit: 'px',
      description: 'bottom offset',
      defaultValue: 0,
    },
    'padding-left': {
      label: 'padding-left',
      type: 'number',
      unit: 'px',
      description: 'left offset',
      defaultValue: 0,
    },
    'padding-right': {
      label: 'padding-right',
      type: 'number',
      unit: 'px',
      description: 'right offset',
      defaultValue: 0,
    },
    'padding-top': {
      label: 'padding-top',
      type: 'number',
      unit: 'px',
      description: 'top offset',
      defaultValue: 0,
    },
    rel: {
      label: 'rel',
      type: 'string',
      description: 'specify the rel attribute for the button link',
      defaultValue: null,
    },
    target: {
      label: 'target',
      type: 'string',
      description: 'specify the target attribute for the button link',
      defaultValue: '_blank',
    },
    'text-align': {
      label: 'text-align',
      type: 'string',
      description: 'text-align button content',
      defaultValue: 'none',
    },
    'text-decoration': {
      label: 'text-decoration',
      type: 'string',
      description: 'underline/overline/none',
      defaultValue: 'none',
    },
    'text-transform': {
      label: 'text-transform',
      type: 'string',
      description: 'capitalize/uppercase/lowercase',
      defaultValue: 'none',
    },
    title: {
      label: 'title',
      type: 'string',
      description: 'tooltip & accessibility',
      defaultValue: null,
    },
    'vertical-align': {
      label: 'vertical-align',
      type: 'string',
      description: 'vertical alignment',
      defaultValue: 'middle',
    },
    width: {
      label: 'width',
      type: 'number/string',
      unit: 'px',
      description: 'button width',
      defaultValue: null,
    },
  },
}

export const MjColumn = {
  title: 'Column',
  tagName: 'mj-column',
  attributes: [],
  description: 'Displays a customizable column.',
  isEndingTag: false,
  allowedChildren: [
    // MjText,
    // MjImage,
    MjButton,
  ],
}

export const MjSection = {
  title: 'Section',
  tagName: 'mj-section',
  attributes: {},
  isEndingTag: false,
  allowedChildren: [MjColumn],
}

export const MjWrapper = {
  title: 'Wrapper',
  tagName: 'mj-wrapper',
  attributes: {},
  isEndingTag: false,
  allowedChildren: [MjSection],
}
