import { BlockType } from '@prisma/client'

export const defaultAttributes = {
  GLOBAL: {
    paddingTop: '8px',
    paddingRight: '0',
    paddingBottom: '8px',
    paddingLeft: '0',
    fontFamily:
      '-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol',
    fontSize: '16px',
    lineHeight: '1.5',
    containerBackgroundColor: '#ffffff',
    color: '#000000',
  },
  [BlockType.H1]: {
    paddingTop: '0',
    paddingRight: '0',
    paddingBottom: '28px',
    paddingLeft: '0',
    fontSize: '36px',
    lineHeight: '40px',
    fontWeight: '800',
  },
  [BlockType.H2]: {
    paddingTop: '26px',
    paddingRight: '0',
    paddingBottom: '20px',
    paddingLeft: '0',
    fontSize: '24px',
    lineHeight: '32px',
    fontWeight: '700',
  },
  [BlockType.H3]: {
    paddingTop: '32px',
    paddingRight: '0',
    paddingBottom: '8px',
    paddingLeft: '0',
    fontSize: '20px',
    lineHeight: '28px',
    fontWeight: '600',
  },
  [BlockType.TEXT]: {
    paddingTop: '12px',
    paddingRight: '0',
    paddingBottom: '12px',
    paddingLeft: '0',
    fontSize: '16px',
    lineHeight: '1.25',
    fontWeight: '400',
  },
  // .with(BlockType.QUOTE, {
  //   paddingTop: '12px',
  //   paddingRight: '0',
  //   paddingBottom: '12px',
  //   paddingLeft: '0',
  //   fontSize: '16px',
  //   lineHeight: '18px',
  //   fontWeight: '400',
  // })
  [BlockType.CODE]: {
    paddingTop: '8px',
    paddingRight: '0',
    paddingBottom: '8px',
    paddingLeft: '0',
    fontSize: '16px',
    lineHeight: '18px',
    fontWeight: '400',
    theme: 'dracula',
    language: 'markup',
  },
  [BlockType.DIVIDER]: {
    paddingTop: '10px',
    paddingRight: '24px',
    paddingBottom: '10px',
    paddingLeft: '24px',
    borderColor: '#000000',
    borderWidth: '2px',
  },
  [BlockType.IMAGE]: {
    paddingTop: '8px',
    paddingRight: '0',
    paddingBottom: '8px',
    paddingLeft: '0',
    src: '',
    alt: '',
  },
  [BlockType.BUTTON]: {
    paddingTop: '8px',
    paddingRight: '0',
    paddingBottom: '8px',
    paddingLeft: '0',
    innerPaddingTop: '12px',
    innerPaddingRight: '24px',
    innerPaddingBottom: '12px',
    innerPaddingLeft: '24px',
    fontSize: '16px',
    fontWeight: '700',
    lineHeight: '1.25',
    width: 'auto',
    // height: '40px',
    backgroundColor: '#414141',
    containerBackgroundColor: '#ffffff',
    borderRadius: '6px',
    color: '#ffffff',
    href: '',
  },
}
